# Generation of the geometry and the meshes of the 3D model of the human eyeball

## Generate the geometry and the initial mesh

Generate the geometry of the human eyeball with the following command:

[source, bash]
----
salome [-t] construct-eye.py [--geometrical_args...]
----

And generate the meshes with the following command:

[source, bash]
----
salome [-t] eye.py
----

To be utilized with Feel++, the mesh must be converted to the Gmsh format with the following command:

[source, bash]
----
gmsh -0 Eye_Mesh3D.med -o Eye_Mesh3D.msh
----




## Generate the uniform family mesh `M`

To generate the uniform family mesh `M`, run the following command:

[source, bash]
----
python3 generate_familly_M.py
----

It will generate the meshes `M0`, `M1`, `M2`, `M3`, `M4` and `M5` of various refinement levels.

To east the usage of the meshed in parallel with Feel++, the meshes need to be partitionned.
This can be performed with the following command:

[source, bash]
----
./partition_mesh_M.sh
----


## Generate the adapted mesh `Mr`

The mesh `Mr` is generated by adapting `M` with a tinier refinement level around the aqueous humor part.
At this point, the pipeline to perform the mesh refinement with the tools of Feel++ is quite tricky, but the script `generate_Mr.sh` permit to do it:

[source, bash]
----
./generate_mesh_Mr.sh
----