= Generation of the geometry and the meshes of the 3D model of the human eyeball

This document describes the procedure to generate the geometry and the meshes of the 3D model of the human eyeball.
To generate the geometry and the meshes, the following tools are needed:

- Salome <<S>> (v9.12.0) https://www.salome-platform.org/
- Feel++ <<F>> (0.111.0) https://docs.feelpp.org/home/index.html

== Generate the geometry and the initial mesh

Generate the geometry of the human eyeball with the following command:

[source, bash]
----
salome [-t] construct-eye.py [--geometrical_args...]
----

And generate the meshes with the following command:

[source, bash]
----
salome [-t] eye.py
----

To be utilized with Feel++, the mesh must be converted to the Gmsh format with the following command:

[source, bash]
----
gmsh -0 Eye_Mesh3D.med -o Eye_Mesh3D.msh
----




== Generate the uniform family mesh `M.`

To generate the uniform family mesh `M.`, run the following command:

[source, bash]
----
python3 generate_familly.py
----

It will generate the meshes `M0`, `M1`, `M2`, `M3`, `M4` and `M5` of various refinement levels.

To east the usage of the meshed in parallel with Feel++, the meshes need to be partitionned.
This can be performed with the following command:

[source, bash]
----
./partition_mesh_M.sh
----


== Generate the adapted mesh `Mr`

The mesh `Mr` is generated by adapting `M` with a tinier refinement level around the aqueous humor part.
At this point, the pipeline to perform the mesh refinement with the tools of Feel++ is quite tricky, but the script `generate_Mr.sh` permit to do it:

[source, bash]
----
./generate_mesh_Mr.sh
----


== Generate the adapted family mesh `Mr.`

The adapted family mesh `Mr.` is generated by remeshing the mesh `Mr` with the following command:

[source, bash]
----
python3 generate_familly.py Mr
----


== Partition the adapted family mesh `Mr.`

To partition the adapted family mesh `Mr.`, run the following command:

[source, bash]
----
./partition_mesh_Mr.sh
----

NOTE: With this partitionnement, the parts where the physics are considered are split: namely the `AqueousHumor` on the one hand where the coupled model is considered, and the remaining regions on the other hand, where the sole heat transfer is considered, see <<C>> for more details.


[bibliography]
== Bibliography

* [[S]] Alejandro Ribes, Adrien Bruneton, Anthony Geay. SALOME: an Open-Source simulation platform integrating ParaView. (2017) https://doi.org/10.13140/RG.2.2.12107.08485.
* [[F]] Christophe Prud'homme, Vincent Chabannes, Thomas Saigre, Christophe Trophime, Luca Berti, Abdoulaye Samaké, Céline Van Landeghem, et al. « Feelpp/feelpp: Feel++ Release V111 Preview.10 ». Zenodo, 15 juillet 2024. https://doi.org/10.5281/zenodo.12742155.
* [[C]] Thomas Saigre, Vincent Chabannes, Christophe Prud'homme, Marcela Szopos. A coupled model of heat transfer and fluid flow in the human eye. (2024). _In preparation_.
