name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: self-ubuntu-24.04
    # container:
      # image: shivanandvp/salome:latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Construct eye STP and generate meshes
        run: |
          docker run --rm -v .:/home/salome shivanandvp/salome:latest salome -t /home/salome/construct-eye-STP.py
          docker run --rm -v .:/home/salome shivanandvp/salome:latest salome -t /home/salome/eye.py

      - name: Convert mesh to Gmsh format
        run: |
          /data/saigre/gmsh-4.13.1-Linux64/bin/gmsh -0 mesh/Eye_Mesh3D.med -o mesh/Eye_Mesh3D.msh

      - name: Tests load mesh and run heat toolbox
        run: |
          cd mesh
          python3 tests/test_mesh.py
          mpirun -np 4 python3 tests/test_mesh.py

      - name: Test with quickstart laplacian
        run: |
          cd mesh
          bash tests/run_laplacian.sh

      - name: Mesh adaptation around AC and PC
        run: |
          cd mesh
          bash generate_mesh_Mr.sh

      - name: Test on volumes
        run: |
          cd mesh
          python3 tests/test_measures.py only_main
